# Generated by Django 6.0.1 on 2026-02-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_end_time_service_is_recurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
