# Generated by Django 6.0.1 on 2026-02-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='generated_until',
            field=models.DateField(blank=True, help_text='Last date instances were generated until', null=True),
        ),
    ]
