# Generated by Django 6.0.1 on 2026-02-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_is_auto_marked_attendance_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.CharField(choices=[('check_in', 'QR Code Check-In'), ('manual', 'Manual Entry'), ('auto', 'Automatic (end of service)')], default='manual', help_text='Source of attendance marking: QR check-in, manual entry, or automatic at service end', max_length=20),
        ),
    ]
