# Generated by Django 6.0.1 on 2026-02-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.CharField(blank=True, choices=[('group_a', 'Group A'), ('group_b', 'Group B'), ('group_c', 'Group C'), ('group_d', 'Group D')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_visitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(blank=True, choices=[('worship', 'Worship'), ('outreach', 'Outreach'), ('youth', 'Youth'), ('administration', 'Administration')], max_length=100, null=True),
        ),
    ]
