# Generated by Django 6.0.1 on 2026-02-14 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_group_member_is_visitor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='attendance_status',
            field=models.CharField(choices=[('active', 'Active - Good Attendance'), ('at_risk', 'At Risk - Pattern Change'), ('inactive', 'Inactive - Extended Absence'), ('vacation', 'On Vacation')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='consecutive_absences',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='engagement_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='member',
            name='last_attendance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_contact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='pastoral_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS Text'), ('phone', 'Phone Call'), ('visit', 'In-Person Visit'), ('small_group', 'Small Group Leader Check-in'), ('social_media', 'Social Media Message')], max_length=20)),
                ('message_sent', models.TextField()),
                ('contacted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('response_received', models.TextField(blank=True, null=True)),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='members.member')),
            ],
            options={
                'ordering': ['-contact_date'],
            },
        ),
        migrations.CreateModel(
            name='MemberAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('early_warning', 'Early Warning - 2 absences'), ('at_risk', 'At Risk - 4+ absences'), ('critical', 'Critical - 8+ absences')], max_length=20)),
                ('reason', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
