# Generated by Django 6.0.1 on 2026-02-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_attendance_status_member_consecutive_absences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='baptised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
