# Generated by Django 6.0.1 on 2026-02-22 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_baptised_member_confirmed_member_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='current_absenteeism_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='MemberAbsenteeismAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('early_warning', 'Early Warning - 25-39% absent'), ('at_risk', 'At Risk - 40-59% absent'), ('critical', 'Critical - 60%+ absent')], max_length=20)),
                ('absenteeism_ratio_at_creation', models.FloatField()),
                ('absent_count_at_creation', models.IntegerField()),
                ('total_services_at_creation', models.IntegerField()),
                ('reason', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absenteeism_alerts', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberAbsenteeismMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_services', models.IntegerField(default=0)),
                ('absent_count', models.IntegerField(default=0)),
                ('present_count', models.IntegerField(default=0)),
                ('weighted_absent', models.FloatField(default=0.0)),
                ('weighted_total', models.FloatField(default=0.0)),
                ('absenteeism_ratio', models.FloatField(default=0.0)),
                ('recurring_absent', models.IntegerField(default=0)),
                ('recurring_present', models.IntegerField(default=0)),
                ('onetime_absent', models.IntegerField(default=0)),
                ('onetime_present', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='absenteeism_metric', to='members.member')),
            ],
            options={
                'verbose_name_plural': 'Member Absenteeism Metrics',
            },
        ),
    ]
