# Generated by Django 6.0.1 on 2026-03-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_add_qr_code_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
        migrations.RemoveField(
            model_name='member',
            name='location',
        ),
        migrations.AddField(
            model_name='member',
            name='class_name',
            field=models.CharField(blank=True, choices=[('airport', 'Airport'), ('abesim', 'Abesim'), ('old_abesim', 'Old Abesim'), ('asufufu_adomako', 'Asufufu / Adomako'), ('baakoniaba', 'Baakoniaba'), ('berlin_top_class_1', 'Berlin Top class 1'), ('berlin_top_class_2', 'Berlin Top class 2'), ('penkwase_class_1', 'Penkwase class 1'), ('penkwase_class_2', 'Penkwase class 2'), ('mayfair', 'Mayfair'), ('odumase', 'Odumase'), ('new_dormaa_kotokrom', 'New Dormaa / Kotokrom'), ('dumasua', 'Dumasua'), ('fiapre_class_1', 'Fiapre Class 1'), ('fiapre_class_2', 'Fiapre Class 2'), ('magazine', 'Magazine'), ('town_centre', 'Town Centre'), ('newton_estate', 'Newton/Estate'), ('distance', 'Distance')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='committee',
            field=models.CharField(blank=True, choices=[('finance', 'Finance'), ('audit', 'Audit'), ('project', 'Project'), ('life_builders', 'Life Builders'), ('health', 'Health'), ('welfare', 'Welfare'), ('harvest', 'Harvest')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='place_of_residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(blank=True, choices=[('technical', 'Technical'), ('media', 'Media'), ('echoes_of_grace', 'Echoes of Grace'), ('celestial_harmony_choir', 'Celestial Harmony Choir'), ('heavenly_vibes', 'Heavenly Vibes'), ('prayer_evangelism', 'Prayer and Evangelism'), ('visitor_care', 'Visitor Care'), ('protocol_ushering', 'Protocol & Ushering')], max_length=100, null=True),
        ),
    ]
