# Generated by Django 6.0.1 on 2026-04-13 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_member_group_remove_member_location_and_more'),
        ('services', '0004_service_generated_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_absences', models.IntegerField(default=2, help_text='Minimum consecutive absences to trigger alert badge notification')),
                ('service_filter_type', models.CharField(choices=[('all', 'All Services (Recurring + Non-Recurring)'), ('recurrent_only', 'Recurring Services Only')], default='all', help_text='Whether to count all services or only recurring service sessions', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_recurring_service', models.ForeignKey(blank=True, help_text='The recurring service to focus on when counting absences', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_config', to='services.service')),
            ],
            options={
                'verbose_name': 'Alert Configuration',
                'verbose_name_plural': 'Alert Configuration',
            },
        ),
    ]
