# Generated by Django 6.0.1 on 2026-04-15 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alertconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='class_name',
            field=models.CharField(blank=True, choices=[('airport', 'Airport'), ('abesim', 'Abesim'), ('old_abesim', 'Old Abesim'), ('asufufu_adomako', 'Asufufu / Adomako'), ('baakoniaba', 'Baakoniaba'), ('berlin_top_class_1', 'Berlin Top class 1'), ('berlin_top_class_2', 'Berlin Top class 2'), ('penkwase_class_1', 'Penkwase class 1'), ('penkwase_class_2', 'Penkwase class 2'), ('mayfair', 'Mayfair'), ('odumase', 'Odumase'), ('new_dormaa_kotokrom', 'New Dormaa / Kotokrom'), ('dumasua', 'Dumasua'), ('fiapre_class_1', 'Fiapre Class 1'), ('fiapre_class_2', 'Fiapre Class 2'), ('magazine', 'Magazine'), ('town_centre', 'Town Centre'), ('newtown_estate', 'Newtown/Estate'), ('distance', 'Distance')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('email', models.EmailField(blank=True, help_text='If set, code can only be used with this email', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Invitation code expires after this date')),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_codes_created', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_with_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AlertConfiguration',
        ),
    ]
