# Generated by Django 6.0.1 on 2026-04-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_fix_newton_estate_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
