# Generated by Django 6.0.1 on 2026-08-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_recalculate_consecutive_absences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberabsenteeismmetric',
            options={'ordering': ['-absenteeism_ratio', '-last_updated'], 'verbose_name_plural': 'Member Absenteeism Metrics'},
        ),
    ]
